import support_line as sline

testFilter = sline.SupportLine(6)
testFilter.reset_support_line()
testFilter.update_support_line(10)
testFilter.update_support_line(10)
testFilter.update_support_line(10)
testFilter.update_support_line(20)
testFilter.update_support_line(20)
testFilter.update_support_line(30)
testFilter.update_support_line(30)
testFilter.update_support_line(30)
print(testFilter.get_support_point())
testFilter.update_support_line(25)
testFilter.update_support_line(25)
testFilter.update_support_line(60)
testFilter.update_support_line(60)
testFilter.update_support_line(60)
testFilter.update_support_line(27)
testFilter.update_support_line(70)
testFilter.update_support_line(70)
testFilter.update_support_line(60)
testFilter.update_support_line(60)
testFilter.update_support_line(60)
testFilter.update_support_line(60)
testFilter.update_support_line(60)